# fly.toml app configuration file generated for writespace-documentservice on 2023-09-06T17:20:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "writespace-documentservice"
primary_region = "otp"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
